// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timber_LOG_CONS
int timber_LOG_CONS();
RcppExport SEXP timber_timber_LOG_CONS() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_CONS());
    return __result;
END_RCPP
}
// timber_LOG_NDELAY
int timber_LOG_NDELAY();
RcppExport SEXP timber_timber_LOG_NDELAY() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_NDELAY());
    return __result;
END_RCPP
}
// timber_LOG_NOWAIT
int timber_LOG_NOWAIT();
RcppExport SEXP timber_timber_LOG_NOWAIT() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_NOWAIT());
    return __result;
END_RCPP
}
// timber_LOG_ODELAY
int timber_LOG_ODELAY();
RcppExport SEXP timber_timber_LOG_ODELAY() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_ODELAY());
    return __result;
END_RCPP
}
// timber_LOG_PERROR
int timber_LOG_PERROR();
RcppExport SEXP timber_timber_LOG_PERROR() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_PERROR());
    return __result;
END_RCPP
}
// timber_LOG_PID
int timber_LOG_PID();
RcppExport SEXP timber_timber_LOG_PID() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_PID());
    return __result;
END_RCPP
}
// timber_LOG_AUTH
int timber_LOG_AUTH();
RcppExport SEXP timber_timber_LOG_AUTH() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_AUTH());
    return __result;
END_RCPP
}
// timber_LOG_AUTHPRIV
int timber_LOG_AUTHPRIV();
RcppExport SEXP timber_timber_LOG_AUTHPRIV() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_AUTHPRIV());
    return __result;
END_RCPP
}
// timber_LOG_CONSOLE
int timber_LOG_CONSOLE();
RcppExport SEXP timber_timber_LOG_CONSOLE() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_CONSOLE());
    return __result;
END_RCPP
}
// timber_LOG_CRON
int timber_LOG_CRON();
RcppExport SEXP timber_timber_LOG_CRON() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_CRON());
    return __result;
END_RCPP
}
// timber_LOG_DAEMON
int timber_LOG_DAEMON();
RcppExport SEXP timber_timber_LOG_DAEMON() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_DAEMON());
    return __result;
END_RCPP
}
// timber_LOG_FTP
int timber_LOG_FTP();
RcppExport SEXP timber_timber_LOG_FTP() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_FTP());
    return __result;
END_RCPP
}
// timber_LOG_KERN
int timber_LOG_KERN();
RcppExport SEXP timber_timber_LOG_KERN() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_KERN());
    return __result;
END_RCPP
}
// timber_LOG_LPR
int timber_LOG_LPR();
RcppExport SEXP timber_timber_LOG_LPR() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LPR());
    return __result;
END_RCPP
}
// timber_LOG_MAIL
int timber_LOG_MAIL();
RcppExport SEXP timber_timber_LOG_MAIL() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_MAIL());
    return __result;
END_RCPP
}
// timber_LOG_NEWS
int timber_LOG_NEWS();
RcppExport SEXP timber_timber_LOG_NEWS() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_NEWS());
    return __result;
END_RCPP
}
// timber_LOG_NTP
int timber_LOG_NTP();
RcppExport SEXP timber_timber_LOG_NTP() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_NTP());
    return __result;
END_RCPP
}
// timber_LOG_SECURITY
int timber_LOG_SECURITY();
RcppExport SEXP timber_timber_LOG_SECURITY() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_SECURITY());
    return __result;
END_RCPP
}
// timber_LOG_SYSLOG
int timber_LOG_SYSLOG();
RcppExport SEXP timber_timber_LOG_SYSLOG() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_SYSLOG());
    return __result;
END_RCPP
}
// timber_LOG_USER
int timber_LOG_USER();
RcppExport SEXP timber_timber_LOG_USER() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_USER());
    return __result;
END_RCPP
}
// timber_LOG_UUCP
int timber_LOG_UUCP();
RcppExport SEXP timber_timber_LOG_UUCP() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_UUCP());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL1
int timber_LOG_LOCAL1();
RcppExport SEXP timber_timber_LOG_LOCAL1() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL1());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL2
int timber_LOG_LOCAL2();
RcppExport SEXP timber_timber_LOG_LOCAL2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL2());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL3
int timber_LOG_LOCAL3();
RcppExport SEXP timber_timber_LOG_LOCAL3() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL3());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL4
int timber_LOG_LOCAL4();
RcppExport SEXP timber_timber_LOG_LOCAL4() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL4());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL5
int timber_LOG_LOCAL5();
RcppExport SEXP timber_timber_LOG_LOCAL5() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL5());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL6
int timber_LOG_LOCAL6();
RcppExport SEXP timber_timber_LOG_LOCAL6() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL6());
    return __result;
END_RCPP
}
// timber_LOG_LOCAL7
int timber_LOG_LOCAL7();
RcppExport SEXP timber_timber_LOG_LOCAL7() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_LOCAL7());
    return __result;
END_RCPP
}
// timber_openlog
void timber_openlog(std::string log_name, int option, int facility);
RcppExport SEXP timber_timber_openlog(SEXP log_nameSEXP, SEXP optionSEXP, SEXP facilitySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type log_name(log_nameSEXP);
    Rcpp::traits::input_parameter< int >::type option(optionSEXP);
    Rcpp::traits::input_parameter< int >::type facility(facilitySEXP);
    timber_openlog(log_name, option, facility);
    return R_NilValue;
END_RCPP
}
// timber_LOG_EMERG
int timber_LOG_EMERG();
RcppExport SEXP timber_timber_LOG_EMERG() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_EMERG());
    return __result;
END_RCPP
}
// timber_LOG_ALERT
int timber_LOG_ALERT();
RcppExport SEXP timber_timber_LOG_ALERT() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_ALERT());
    return __result;
END_RCPP
}
// timber_LOG_CRIT
int timber_LOG_CRIT();
RcppExport SEXP timber_timber_LOG_CRIT() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_CRIT());
    return __result;
END_RCPP
}
// timber_LOG_ERR
int timber_LOG_ERR();
RcppExport SEXP timber_timber_LOG_ERR() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_ERR());
    return __result;
END_RCPP
}
// timber_LOG_WARNING
int timber_LOG_WARNING();
RcppExport SEXP timber_timber_LOG_WARNING() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_WARNING());
    return __result;
END_RCPP
}
// timber_LOG_NOTICE
int timber_LOG_NOTICE();
RcppExport SEXP timber_timber_LOG_NOTICE() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_NOTICE());
    return __result;
END_RCPP
}
// timber_LOG_INFO
int timber_LOG_INFO();
RcppExport SEXP timber_timber_LOG_INFO() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_INFO());
    return __result;
END_RCPP
}
// timber_LOG_DEBUG
int timber_LOG_DEBUG();
RcppExport SEXP timber_timber_LOG_DEBUG() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(timber_LOG_DEBUG());
    return __result;
END_RCPP
}
// timber_log
void timber_log(int type, std::string message);
RcppExport SEXP timber_timber_log(SEXP typeSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type message(messageSEXP);
    timber_log(type, message);
    return R_NilValue;
END_RCPP
}
// timber_closelog
void timber_closelog();
RcppExport SEXP timber_timber_closelog() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    timber_closelog();
    return R_NilValue;
END_RCPP
}
