# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timber_LOG_CONS <- function() {
    .Call('timber_timber_LOG_CONS', PACKAGE = 'timber')
}

timber_LOG_NDELAY <- function() {
    .Call('timber_timber_LOG_NDELAY', PACKAGE = 'timber')
}

timber_LOG_NOWAIT <- function() {
    .Call('timber_timber_LOG_NOWAIT', PACKAGE = 'timber')
}

timber_LOG_ODELAY <- function() {
    .Call('timber_timber_LOG_ODELAY', PACKAGE = 'timber')
}

timber_LOG_PERROR <- function() {
    .Call('timber_timber_LOG_PERROR', PACKAGE = 'timber')
}

timber_LOG_PID <- function() {
    .Call('timber_timber_LOG_PID', PACKAGE = 'timber')
}

timber_LOG_AUTH <- function() {
    .Call('timber_timber_LOG_AUTH', PACKAGE = 'timber')
}

timber_LOG_AUTHPRIV <- function() {
    .Call('timber_timber_LOG_AUTHPRIV', PACKAGE = 'timber')
}

timber_LOG_CONSOLE <- function() {
    .Call('timber_timber_LOG_CONSOLE', PACKAGE = 'timber')
}

timber_LOG_CRON <- function() {
    .Call('timber_timber_LOG_CRON', PACKAGE = 'timber')
}

timber_LOG_DAEMON <- function() {
    .Call('timber_timber_LOG_DAEMON', PACKAGE = 'timber')
}

timber_LOG_FTP <- function() {
    .Call('timber_timber_LOG_FTP', PACKAGE = 'timber')
}

timber_LOG_KERN <- function() {
    .Call('timber_timber_LOG_KERN', PACKAGE = 'timber')
}

timber_LOG_LPR <- function() {
    .Call('timber_timber_LOG_LPR', PACKAGE = 'timber')
}

timber_LOG_MAIL <- function() {
    .Call('timber_timber_LOG_MAIL', PACKAGE = 'timber')
}

timber_LOG_NEWS <- function() {
    .Call('timber_timber_LOG_NEWS', PACKAGE = 'timber')
}

timber_LOG_NTP <- function() {
    .Call('timber_timber_LOG_NTP', PACKAGE = 'timber')
}

timber_LOG_SECURITY <- function() {
    .Call('timber_timber_LOG_SECURITY', PACKAGE = 'timber')
}

timber_LOG_SYSLOG <- function() {
    .Call('timber_timber_LOG_SYSLOG', PACKAGE = 'timber')
}

timber_LOG_USER <- function() {
    .Call('timber_timber_LOG_USER', PACKAGE = 'timber')
}

timber_LOG_UUCP <- function() {
    .Call('timber_timber_LOG_UUCP', PACKAGE = 'timber')
}

timber_LOG_LOCAL1 <- function() {
    .Call('timber_timber_LOG_LOCAL1', PACKAGE = 'timber')
}

timber_LOG_LOCAL2 <- function() {
    .Call('timber_timber_LOG_LOCAL2', PACKAGE = 'timber')
}

timber_LOG_LOCAL3 <- function() {
    .Call('timber_timber_LOG_LOCAL3', PACKAGE = 'timber')
}

timber_LOG_LOCAL4 <- function() {
    .Call('timber_timber_LOG_LOCAL4', PACKAGE = 'timber')
}

timber_LOG_LOCAL5 <- function() {
    .Call('timber_timber_LOG_LOCAL5', PACKAGE = 'timber')
}

timber_LOG_LOCAL6 <- function() {
    .Call('timber_timber_LOG_LOCAL6', PACKAGE = 'timber')
}

timber_LOG_LOCAL7 <- function() {
    .Call('timber_timber_LOG_LOCAL7', PACKAGE = 'timber')
}

timber_openlog <- function(log_name, option, facility) {
    invisible(.Call('timber_timber_openlog', PACKAGE = 'timber', log_name, option, facility))
}

timber_LOG_EMERG <- function() {
    .Call('timber_timber_LOG_EMERG', PACKAGE = 'timber')
}

timber_LOG_ALERT <- function() {
    .Call('timber_timber_LOG_ALERT', PACKAGE = 'timber')
}

timber_LOG_CRIT <- function() {
    .Call('timber_timber_LOG_CRIT', PACKAGE = 'timber')
}

timber_LOG_ERR <- function() {
    .Call('timber_timber_LOG_ERR', PACKAGE = 'timber')
}

timber_LOG_WARNING <- function() {
    .Call('timber_timber_LOG_WARNING', PACKAGE = 'timber')
}

timber_LOG_NOTICE <- function() {
    .Call('timber_timber_LOG_NOTICE', PACKAGE = 'timber')
}

timber_LOG_INFO <- function() {
    .Call('timber_timber_LOG_INFO', PACKAGE = 'timber')
}

timber_LOG_DEBUG <- function() {
    .Call('timber_timber_LOG_DEBUG', PACKAGE = 'timber')
}

timber_log <- function(type, message) {
    invisible(.Call('timber_timber_log', PACKAGE = 'timber', type, message))
}

timber_closelog <- function() {
    invisible(.Call('timber_timber_closelog', PACKAGE = 'timber'))
}

